// This file is auto-generated by @tanstack/router-vite-plugin
// It will be populated when you run `vite dev` or `vite build`
// Do not manually edit this file

import { createRootRoute } from "@tanstack/react-router";

export const routeTree = createRootRoute();
