/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantInactiveRouteImport } from './routes/restaurant-inactive'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppKitchenIndexRouteImport } from './routes/_app/kitchen/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppWaiterTablesRouteImport } from './routes/_app/waiter/tables'
import { Route as AppPlatformUsersRouteImport } from './routes/_app/platform/users'
import { Route as AppPlatformSettingsRouteImport } from './routes/_app/platform/settings'
import { Route as AppPlatformPendingUsersRouteImport } from './routes/_app/platform/pending-users'
import { Route as AppCashierTablesRouteImport } from './routes/_app/cashier/tables'
import { Route as AppAdminTablesRouteImport } from './routes/_app/admin/tables'
import { Route as AppAdminStaffRouteImport } from './routes/_app/admin/staff'
import { Route as AppAdminReportsRouteImport } from './routes/_app/admin/reports'
import { Route as AppAdminMenuRouteImport } from './routes/_app/admin/menu'
import { Route as AppAdminInventoryRouteImport } from './routes/_app/admin/inventory'
import { Route as AppWaiterOrdersIndexRouteImport } from './routes/_app/waiter/orders.index'
import { Route as AppPlatformRestaurantsIndexRouteImport } from './routes/_app/platform/restaurants.index'
import { Route as AppWaiterOrdersIdRouteImport } from './routes/_app/waiter/orders.$id'
import { Route as AppPlatformRestaurantsRestaurantIdRouteImport } from './routes/_app/platform/restaurants.$restaurantId'
import { Route as AppCashierOrdersIdRouteImport } from './routes/_app/cashier/orders.$id'

const RestaurantInactiveRoute = RestaurantInactiveRouteImport.update({
  id: '/restaurant-inactive',
  path: '/restaurant-inactive',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKitchenIndexRoute = AppKitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppWaiterTablesRoute = AppWaiterTablesRouteImport.update({
  id: '/waiter/tables',
  path: '/waiter/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformUsersRoute = AppPlatformUsersRouteImport.update({
  id: '/platform/users',
  path: '/platform/users',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformSettingsRoute = AppPlatformSettingsRouteImport.update({
  id: '/platform/settings',
  path: '/platform/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformPendingUsersRoute = AppPlatformPendingUsersRouteImport.update({
  id: '/platform/pending-users',
  path: '/platform/pending-users',
  getParentRoute: () => AppRoute,
} as any)
const AppCashierTablesRoute = AppCashierTablesRouteImport.update({
  id: '/cashier/tables',
  path: '/cashier/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTablesRoute = AppAdminTablesRouteImport.update({
  id: '/admin/tables',
  path: '/admin/tables',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStaffRoute = AppAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminMenuRoute = AppAdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminInventoryRoute = AppAdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppWaiterOrdersIndexRoute = AppWaiterOrdersIndexRouteImport.update({
  id: '/waiter/orders/',
  path: '/waiter/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformRestaurantsIndexRoute =
  AppPlatformRestaurantsIndexRouteImport.update({
    id: '/platform/restaurants/',
    path: '/platform/restaurants/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWaiterOrdersIdRoute = AppWaiterOrdersIdRouteImport.update({
  id: '/waiter/orders/$id',
  path: '/waiter/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformRestaurantsRestaurantIdRoute =
  AppPlatformRestaurantsRestaurantIdRouteImport.update({
    id: '/platform/restaurants/$restaurantId',
    path: '/platform/restaurants/$restaurantId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCashierOrdersIdRoute = AppCashierOrdersIdRouteImport.update({
  id: '/cashier/orders/$id',
  path: '/cashier/orders/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/restaurant-inactive': typeof RestaurantInactiveRoute
  '/admin/inventory': typeof AppAdminInventoryRoute
  '/admin/menu': typeof AppAdminMenuRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/staff': typeof AppAdminStaffRoute
  '/admin/tables': typeof AppAdminTablesRoute
  '/cashier/tables': typeof AppCashierTablesRoute
  '/platform/pending-users': typeof AppPlatformPendingUsersRoute
  '/platform/settings': typeof AppPlatformSettingsRoute
  '/platform/users': typeof AppPlatformUsersRoute
  '/waiter/tables': typeof AppWaiterTablesRoute
  '/admin/': typeof AppAdminIndexRoute
  '/kitchen/': typeof AppKitchenIndexRoute
  '/cashier/orders/$id': typeof AppCashierOrdersIdRoute
  '/platform/restaurants/$restaurantId': typeof AppPlatformRestaurantsRestaurantIdRoute
  '/waiter/orders/$id': typeof AppWaiterOrdersIdRoute
  '/platform/restaurants/': typeof AppPlatformRestaurantsIndexRoute
  '/waiter/orders/': typeof AppWaiterOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/restaurant-inactive': typeof RestaurantInactiveRoute
  '/admin/inventory': typeof AppAdminInventoryRoute
  '/admin/menu': typeof AppAdminMenuRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/staff': typeof AppAdminStaffRoute
  '/admin/tables': typeof AppAdminTablesRoute
  '/cashier/tables': typeof AppCashierTablesRoute
  '/platform/pending-users': typeof AppPlatformPendingUsersRoute
  '/platform/settings': typeof AppPlatformSettingsRoute
  '/platform/users': typeof AppPlatformUsersRoute
  '/waiter/tables': typeof AppWaiterTablesRoute
  '/admin': typeof AppAdminIndexRoute
  '/kitchen': typeof AppKitchenIndexRoute
  '/cashier/orders/$id': typeof AppCashierOrdersIdRoute
  '/platform/restaurants/$restaurantId': typeof AppPlatformRestaurantsRestaurantIdRoute
  '/waiter/orders/$id': typeof AppWaiterOrdersIdRoute
  '/platform/restaurants': typeof AppPlatformRestaurantsIndexRoute
  '/waiter/orders': typeof AppWaiterOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/restaurant-inactive': typeof RestaurantInactiveRoute
  '/_app/admin/inventory': typeof AppAdminInventoryRoute
  '/_app/admin/menu': typeof AppAdminMenuRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/staff': typeof AppAdminStaffRoute
  '/_app/admin/tables': typeof AppAdminTablesRoute
  '/_app/cashier/tables': typeof AppCashierTablesRoute
  '/_app/platform/pending-users': typeof AppPlatformPendingUsersRoute
  '/_app/platform/settings': typeof AppPlatformSettingsRoute
  '/_app/platform/users': typeof AppPlatformUsersRoute
  '/_app/waiter/tables': typeof AppWaiterTablesRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/kitchen/': typeof AppKitchenIndexRoute
  '/_app/cashier/orders/$id': typeof AppCashierOrdersIdRoute
  '/_app/platform/restaurants/$restaurantId': typeof AppPlatformRestaurantsRestaurantIdRoute
  '/_app/waiter/orders/$id': typeof AppWaiterOrdersIdRoute
  '/_app/platform/restaurants/': typeof AppPlatformRestaurantsIndexRoute
  '/_app/waiter/orders/': typeof AppWaiterOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/pending'
    | '/restaurant-inactive'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/tables'
    | '/cashier/tables'
    | '/platform/pending-users'
    | '/platform/settings'
    | '/platform/users'
    | '/waiter/tables'
    | '/admin/'
    | '/kitchen/'
    | '/cashier/orders/$id'
    | '/platform/restaurants/$restaurantId'
    | '/waiter/orders/$id'
    | '/platform/restaurants/'
    | '/waiter/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/pending'
    | '/restaurant-inactive'
    | '/admin/inventory'
    | '/admin/menu'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/tables'
    | '/cashier/tables'
    | '/platform/pending-users'
    | '/platform/settings'
    | '/platform/users'
    | '/waiter/tables'
    | '/admin'
    | '/kitchen'
    | '/cashier/orders/$id'
    | '/platform/restaurants/$restaurantId'
    | '/waiter/orders/$id'
    | '/platform/restaurants'
    | '/waiter/orders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/demo'
    | '/login'
    | '/pending'
    | '/restaurant-inactive'
    | '/_app/admin/inventory'
    | '/_app/admin/menu'
    | '/_app/admin/reports'
    | '/_app/admin/staff'
    | '/_app/admin/tables'
    | '/_app/cashier/tables'
    | '/_app/platform/pending-users'
    | '/_app/platform/settings'
    | '/_app/platform/users'
    | '/_app/waiter/tables'
    | '/_app/admin/'
    | '/_app/kitchen/'
    | '/_app/cashier/orders/$id'
    | '/_app/platform/restaurants/$restaurantId'
    | '/_app/waiter/orders/$id'
    | '/_app/platform/restaurants/'
    | '/_app/waiter/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  RestaurantInactiveRoute: typeof RestaurantInactiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant-inactive': {
      id: '/restaurant-inactive'
      path: '/restaurant-inactive'
      fullPath: '/restaurant-inactive'
      preLoaderRoute: typeof RestaurantInactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/kitchen/': {
      id: '/_app/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof AppKitchenIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waiter/tables': {
      id: '/_app/waiter/tables'
      path: '/waiter/tables'
      fullPath: '/waiter/tables'
      preLoaderRoute: typeof AppWaiterTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/users': {
      id: '/_app/platform/users'
      path: '/platform/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof AppPlatformUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/settings': {
      id: '/_app/platform/settings'
      path: '/platform/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof AppPlatformSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/pending-users': {
      id: '/_app/platform/pending-users'
      path: '/platform/pending-users'
      fullPath: '/platform/pending-users'
      preLoaderRoute: typeof AppPlatformPendingUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashier/tables': {
      id: '/_app/cashier/tables'
      path: '/cashier/tables'
      fullPath: '/cashier/tables'
      preLoaderRoute: typeof AppCashierTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tables': {
      id: '/_app/admin/tables'
      path: '/admin/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AppAdminTablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/staff': {
      id: '/_app/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AppAdminStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/menu': {
      id: '/_app/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AppAdminMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/inventory': {
      id: '/_app/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AppAdminInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waiter/orders/': {
      id: '/_app/waiter/orders/'
      path: '/waiter/orders'
      fullPath: '/waiter/orders/'
      preLoaderRoute: typeof AppWaiterOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/restaurants/': {
      id: '/_app/platform/restaurants/'
      path: '/platform/restaurants'
      fullPath: '/platform/restaurants/'
      preLoaderRoute: typeof AppPlatformRestaurantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waiter/orders/$id': {
      id: '/_app/waiter/orders/$id'
      path: '/waiter/orders/$id'
      fullPath: '/waiter/orders/$id'
      preLoaderRoute: typeof AppWaiterOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platform/restaurants/$restaurantId': {
      id: '/_app/platform/restaurants/$restaurantId'
      path: '/platform/restaurants/$restaurantId'
      fullPath: '/platform/restaurants/$restaurantId'
      preLoaderRoute: typeof AppPlatformRestaurantsRestaurantIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashier/orders/$id': {
      id: '/_app/cashier/orders/$id'
      path: '/cashier/orders/$id'
      fullPath: '/cashier/orders/$id'
      preLoaderRoute: typeof AppCashierOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminInventoryRoute: typeof AppAdminInventoryRoute
  AppAdminMenuRoute: typeof AppAdminMenuRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminStaffRoute: typeof AppAdminStaffRoute
  AppAdminTablesRoute: typeof AppAdminTablesRoute
  AppCashierTablesRoute: typeof AppCashierTablesRoute
  AppPlatformPendingUsersRoute: typeof AppPlatformPendingUsersRoute
  AppPlatformSettingsRoute: typeof AppPlatformSettingsRoute
  AppPlatformUsersRoute: typeof AppPlatformUsersRoute
  AppWaiterTablesRoute: typeof AppWaiterTablesRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppKitchenIndexRoute: typeof AppKitchenIndexRoute
  AppCashierOrdersIdRoute: typeof AppCashierOrdersIdRoute
  AppPlatformRestaurantsRestaurantIdRoute: typeof AppPlatformRestaurantsRestaurantIdRoute
  AppWaiterOrdersIdRoute: typeof AppWaiterOrdersIdRoute
  AppPlatformRestaurantsIndexRoute: typeof AppPlatformRestaurantsIndexRoute
  AppWaiterOrdersIndexRoute: typeof AppWaiterOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminInventoryRoute: AppAdminInventoryRoute,
  AppAdminMenuRoute: AppAdminMenuRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminStaffRoute: AppAdminStaffRoute,
  AppAdminTablesRoute: AppAdminTablesRoute,
  AppCashierTablesRoute: AppCashierTablesRoute,
  AppPlatformPendingUsersRoute: AppPlatformPendingUsersRoute,
  AppPlatformSettingsRoute: AppPlatformSettingsRoute,
  AppPlatformUsersRoute: AppPlatformUsersRoute,
  AppWaiterTablesRoute: AppWaiterTablesRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppKitchenIndexRoute: AppKitchenIndexRoute,
  AppCashierOrdersIdRoute: AppCashierOrdersIdRoute,
  AppPlatformRestaurantsRestaurantIdRoute:
    AppPlatformRestaurantsRestaurantIdRoute,
  AppWaiterOrdersIdRoute: AppWaiterOrdersIdRoute,
  AppPlatformRestaurantsIndexRoute: AppPlatformRestaurantsIndexRoute,
  AppWaiterOrdersIndexRoute: AppWaiterOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  RestaurantInactiveRoute: RestaurantInactiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
